platform :ios, '9.0'

target 'iAirSandbox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iAirSandbox

pod 'Aspects',   '~> 1.4.1'


end
